debug: false
spring:
  application:
    name: dvdtheque-mcp-server
  main:
    banner-mode: off
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7

dvdtheque:
  api:
    base-url: http://localhost:8762/dvdtheque-service
    endpoints:
      get-by-titre: /film/{titre}

logging:
  level:
    org:
      springframework:
        ai: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

server.port: 8060